server:
  port: 8080

spring:
  application:
    name: mock-company-webapp

  datasource:
    url: jdbc:h2:mem:productsdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

